// Generated by https://quicktype.io

export interface HProduct {
    name:           string;
    description:    string;
    image:          string[];
    price:          number;
    numberInStock?: number;
    id?:            string;
}
